### ISSUE TITLE
大佬，这个怎么回事

### ISSUE THREAD

**Issue by GN1028** [hiram64/temporal-ensembling-semi-supervised#1]
Traceback (most recent call last):
  File "D:/all  cx/temporal-ensembling-semi-supervised-master/main_temporal_ensembling.py", line 157, in <module>
    main()
  File "D:/all  cx/temporal-ensembling-semi-supervised-master/main_temporal_ensembling.py", line 61, in main
    train_x, train_y, test_x, test_y = load_data(args.data_path)
  File "D:\all  cx\temporal-ensembling-semi-supervised-master\utils.py", line 11, in load_data
    return data['train_x'], data['train_y'], data['test_x'], data['test_y']
  File "D:\Anacondaaz\envs\python3\lib\site-packages\numpy\lib\npyio.py", line 237, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'train_x is not a file in the archive'

**Comment by elgong** [comment]
参数
